apiVersion: v1
kind: Service
metadata:
  name: interface-repository
  namespace: polyorb
  labels:
    app: interface-repository
    version: v1.0.0
spec:
  type: ClusterIP
  selector:
    app: interface-repository
    version: v1.0.0
  ports:
  - name: grpc
    port: 50066
    targetPort: 50066
    protocol: TCP
