apiVersion: v2
name: polyorb
description: Helm chart for PolyORB Ada microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - polyorb
  - ada
  - corba
  - grpc
  - microservices
maintainers:
  - name: RefactorTeam
    email: team@example.com
sources:
  - https://github.com/heathdorn00/PolyORB
