apiVersion: v1
kind: ConfigMap
metadata:
  name: windows-adapter-config
  namespace: wxwidgets
  labels:
    app: windows-adapter
    version: v1.0.0
data:
  log_level: "info"
  grpc_port: "50054"
  platform: "windows"
  native_rendering: "true"
