apiVersion: v1
kind: Service
metadata:
  name: windows-adapter
  namespace: wxwidgets
  labels:
    app: windows-adapter
    version: v1.0.0
    tier: platform-adapter
spec:
  type: ClusterIP
  selector:
    app: windows-adapter
    version: v1.0.0
  ports:
  - name: grpc
    port: 50054
    targetPort: 50054
    protocol: TCP
