apiVersion: v1
kind: Service
metadata:
  name: polyorb-service
  namespace: polyorb-prod
  labels:
    app: polyorb
spec:
  type: ClusterIP
  selector:
    app: polyorb
  ports:
  - name: corba
    port: 5000
    targetPort: 5000
    protocol: TCP
  sessionAffinity: ClientIP
