apiVersion: v1
kind: ServiceAccount
metadata:
  name: polyorb-service-account
  namespace: polyorb-prod
  labels:
    app: polyorb
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: polyorb-role
  namespace: polyorb-prod
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: polyorb-role-binding
  namespace: polyorb-prod
subjects:
  - kind: ServiceAccount
    name: polyorb-service-account
    namespace: polyorb-prod
roleRef:
  kind: Role
  name: polyorb-role
  apiGroup: rbac.authorization.k8s.io
