apiVersion: v1
kind: Service
metadata:
  name: linux-adapter
  namespace: wxwidgets
  labels:
    app: linux-adapter
    version: v1.0.0
    tier: platform-adapter
spec:
  type: ClusterIP
  selector:
    app: linux-adapter
    version: v1.0.0
  ports:
  - name: grpc
    port: 50056
    targetPort: 50056
    protocol: TCP
