apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: polyorb
  labels:
    app: notification-service
    version: v1.0.0
spec:
  type: ClusterIP
  selector:
    app: notification-service
    version: v1.0.0
  ports:
  - name: grpc
    port: 50065
    targetPort: 50065
    protocol: TCP
