apiVersion: v1
kind: ConfigMap
metadata:
  name: poa-manager-config
  namespace: polyorb
  labels:
    app: poa-manager
    version: v1.0.0
data:
  log_level: "info"
  grpc_port: "50062"
  poa_threads: "4"
