apiVersion: v1
kind: Service
metadata:
  name: poa-manager
  namespace: polyorb
  labels:
    app: poa-manager
    version: v1.0.0
spec:
  type: ClusterIP
  selector:
    app: poa-manager
    version: v1.0.0
  ports:
  - name: grpc
    port: 50062
    targetPort: 50062
    protocol: TCP
